# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastlite-migrations',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/fastlite-migrations',
                'lib_path': 'fastlite_migrations'},
  'syms': {'fastlite_migrations.core': {'fastlite_migrations.core.foo': ('core.html#foo', 'fastlite_migrations/core.py')}}}
